

class Generator:



    # inputs are the arguments of a function or distribution or
    # the function/distribution that produced this model node value/variable.
    def getInputs(self) -> list:
        pass

    # return a unique string representing this graphical model node.
    # For named variables it should be the name.
    def get_unique_id(self) -> str:
        pass


    def get_name(self) -> str:
        pass

    # return a value generated by this generator.
    def generate(self) -> object:
        pass

    def code_string(self) -> str:
        pass

    # return the character symbol, for function '=' and for generative distribution '~'
    def generator_code_char(self) -> str:
        pass

    def get_inputs(self):
        return self.get_params().values()

    def get_params(self) -> dict:
        pass