

class Generator(GraphicalModel):
    def getName(self) -> str:
        pass

    # return a value generated by this generator.
    def generate(self) -> object:
        pass

    def codeString(self) -> str:
        pass

    # return the character symbol, for function '=' and for generative distribution '~'
    def generatorCodeChar(self) -> str:
        pass

    def getInputs(self):
        return self.getParams().values()

    def getParams(self) -> dict:
        pass